//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int MAADMIN { get; set; }
        public string TENQUANLY { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public bool BIKHOA { get; set; }
        public int SOLANDANGNHAPSAI { get; set; }
        public Nullable<System.DateTime> THOIGIANDANGNHAPSAICUOICUNG { get; set; }
        public string SessionToken { get; set; }
    }
}
