//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.SANPHAMTHEOYEUCAUs = new HashSet<SANPHAMTHEOYEUCAU>();
        }
    
        public int MAHOADON { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public string TRANGTHAITHANHTOAN { get; set; }
        public string PHUONGTHUCTHANHTOAN { get; set; }
        public Nullable<int> MANHANVIENTAICHINH { get; set; }
        public Nullable<System.DateTime> NGAYLAP { get; set; }
        public string SOHOADON { get; set; }
        public Nullable<bool> TRANGTHAIHUYDON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAMTHEOYEUCAU> SANPHAMTHEOYEUCAUs { get; set; }
    }
}
