//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIENHE
    {
        public int MALIENHE { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public string HOVATEN { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> SDT { get; set; }
        public string LOINHAN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
