//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SQLWEB2Entities1 : DbContext
    {
        public SQLWEB2Entities1()
            : base("name=SQLWEB2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<DOANHTHU> DOANHTHUs { get; set; }
        public virtual DbSet<GIOHANG> GIOHANGs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LICHSUDANGNHAP> LICHSUDANGNHAPs { get; set; }
        public virtual DbSet<LIENHE> LIENHEs { get; set; }
        public virtual DbSet<NHANVIENSANXUAT> NHANVIENSANXUATs { get; set; }
        public virtual DbSet<NHANVIENTAICHINH> NHANVIENTAICHINHs { get; set; }
        public virtual DbSet<NHANVIENVANCHUYEN> NHANVIENVANCHUYENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<SANPHAMTHEOYEUCAU> SANPHAMTHEOYEUCAUs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIENDOSANXUAT> TIENDOSANXUATs { get; set; }
        public virtual DbSet<VANCHUYEN> VANCHUYENs { get; set; }
    }
}
