//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIENVANCHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIENVANCHUYEN()
        {
            this.VANCHUYENs = new HashSet<VANCHUYEN>();
        }
    
        public int MANHANVIENVANCHUYEN { get; set; }
        public string TENNHANVIENVANCHUYEN { get; set; }
        public int TUOI { get; set; }
        public string DIACHI { get; set; }
        public long SDT { get; set; }
        public long SOCCCD { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public Nullable<System.DateTime> NGAYVAOLAM { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYNGHILAM { get; set; }
        public string VAITRO { get; set; }
        public bool BIKHOA { get; set; }
        public Nullable<int> SOLANDANGNHAPSAI { get; set; }
        public Nullable<System.DateTime> THOIGIANDANGNHAPSAICUOICUNG { get; set; }
        public string SessionToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANCHUYEN> VANCHUYENs { get; set; }
    }
}
