//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAMTHEOYEUCAU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAMTHEOYEUCAU()
        {
            this.DOANHTHUs = new HashSet<DOANHTHU>();
            this.TIENDOSANXUATs = new HashSet<TIENDOSANXUAT>();
            this.VANCHUYENs = new HashSet<VANCHUYEN>();
        }
    
        public int MASANPHAMTHEOYEUCAU { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public string LOAISANPHAM { get; set; }
        public Nullable<double> CHIEUDAI { get; set; }
        public Nullable<double> CHIEURONG { get; set; }
        public Nullable<double> CHIEUCAO { get; set; }
        public string VATLIEU { get; set; }
        public string MAUSAC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> TONGSOTIENSANXUAT { get; set; }
        public string MOTASANPHAM { get; set; }
        public string TRANGTHAIDUYET { get; set; }
        public Nullable<int> MAHOADON { get; set; }
        public string ANHMINHHOA { get; set; }
        public string KHACHHANGCHAPNHAN { get; set; }
        public Nullable<double> TONGTIENSANPHAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOANHTHU> DOANHTHUs { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIENDOSANXUAT> TIENDOSANXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANCHUYEN> VANCHUYENs { get; set; }
    }
}
