//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.GIOHANGs = new HashSet<GIOHANG>();
        }
    
        public int MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string GIASANPHAM { get; set; }
        public string LOAISANPHAM { get; set; }
        public Nullable<double> CHIEUDAI { get; set; }
        public Nullable<double> CHIEURONG { get; set; }
        public Nullable<double> CHIEUCAO { get; set; }
        public string CHATLIEU { get; set; }
        public string MOTASANPHAM { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string ANHSANPHAM { get; set; }
        public Nullable<int> DABAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIOHANG> GIOHANGs { get; set; }
    }
}
