//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBDOGO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIENDOSANXUAT
    {
        public int MATIENDOSANXUAT { get; set; }
        public Nullable<System.DateTime> NGAYSANXUAT { get; set; }
        public Nullable<System.DateTime> NGAYDUKIENHOANTHANH { get; set; }
        public Nullable<System.DateTime> NGAYHOANTHANHTHUCTE { get; set; }
        public string GIAIDOANSANXUAT { get; set; }
        public Nullable<int> MANHANVIENSANXUAT { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> MASANPHAMTHEOYEUCAU { get; set; }
        public string ANHMINHHOA { get; set; }
        public string NGHIEMTHU { get; set; }
    
        public virtual NHANVIENSANXUAT NHANVIENSANXUAT { get; set; }
        public virtual SANPHAMTHEOYEUCAU SANPHAMTHEOYEUCAU { get; set; }
    }
}
